AllCops:
  TargetRubyVersion: 2.5

  Exclude:
    - 'apps/**/*'
    - 'scripts/docker/**/*'

Layout/LineLength:
  Max: 120

# The default is 10, which is low...
Metrics/MethodLength:
  Enabled: false

# The default is 25, which is low...
Metrics/BlockLength:
  Enabled: false

# The default is 3, which is low...
Metrics/BlockNesting:
  Max: 5

# There are loads of calls to colorize which are fairly clear, but drive up AbcSize
# Set to 21 for update_apps (ensures it won't grow)
Metrics/AbcSize:
  Max: 21

Metrics/ParameterLists:
  Max: 7

Style/FrozenStringLiteralComment:
  Enabled: false

# Generating false positives
Style/SafeNavigation:
  Enabled: false

# Generating false positives in elasticsearch shell scripts
Style/FormatStringToken:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 10
