FROM ghcr.io/landregistry/squid:6-20250516-082537@sha256:9f157cde3fcfe03a6f21eb7dcafedf3c29e126cf3630e7e07fa231b8c6dc9153
# We have this as a Dockerfile rather than just specifying the image in the
# compose fragment, to prevent it being deleted in a destroy, so it doesn't
# need to be redownloaded
