FROM ghcr.io/landregistry/squid:7-20260513-123608@sha256:22bb1f86d4e7f7d9f45b78605288c7b5339e07c8661229c7f93eca76f32a9560
# We have this as a Dockerfile rather than just specifying the image in the
# compose fragment, to prevent it being deleted in a destroy, so it doesn't
# need to be redownloaded
