# This is so a reset (dc down) won't remove the base redis image, only the one created from this dockerfile
FROM docker.io/redis:7.4.8@sha256:3e0669e42d4fe421c9dea0ba5fbc04d336b80b4f32a6c7d25bee3a1d089288a1
