services:
  elasticsearch6:
    container_name: elasticsearch6
    build: ../scripts/docker/elasticsearch6
    ports:
      - "9203:9201"
      - "9303:9301"
    restart: on-failure
    platform: "linux/amd64"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK