version: '3.7'
services:
  elasticsearch6:
    container_name: elasticsearch6
    build: ../scripts/docker/elasticsearch6
    ports:
      - "9203:9200"
      - "9303:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    restart: on-failure
