version: "3.7"
services:
  db2_community:
    container_name: db2_community
    build: ../scripts/docker/db2_community/
    ports:
      - "30002:50000"
      - "35002:55000"
    env_file:
      - ../scripts/docker/db2_community/.env_list
    privileged: true
    deploy:
      resources:
        limits:
          memory: 2GB
