version: "2"
services:
  db2_community:
    container_name: db2_community
    build: ../scripts/docker/db2_community/
    ports:
      - "30002:50000"
      - "35002:55000"
    env_file:
      - ../scripts/docker/db2_community/.env_list
    privileged: true
    mem_limit: 2GB
